monolog:
    channels: ['notification']
    handlers:
        notification:
            type: stream
            path: "%kernel.logs_dir%/notification.log"
            level: debug
            channels: ["notification"]
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
            channels: ["!event", "!notification"]
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine", "!console"]
